# Generated by Django 2.0.2 on 2018-03-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_blog_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date', 'views']},
        ),
    ]
