# Generated by Django 2.0.2 on 2018-03-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20180318_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(default='技术', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.BlogCategory'),
        ),
    ]
